name:  check-test
on:  [push]

jobs:
  error_check:
    name: Use Linux Commands
    runs-on: ubuntu-latest
    steps:
      - echo gcd script
      - name: Pemission Setting
        run: chmod +x same.sh dousa_test.sh
      - name: Test Start!
        run: ./dousa_test.sh
