name:  check-test
on:  [push]

jobs:
  scriptk:
    name: Use Linux Commands
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files in kadai4_gcd directory
        run : ls -al

      - name: echo gcd script
        run:  echo gcd script
      - name: Pemission Setting
        run: chmod +x ./dousa_test.sh
      - name: Test Start!
        run: ./dousa_test.sh
